name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run Scala tests
      run: sbt coverage test coverageReport coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Deploy to Heroku
      run: sbt herokuDeploy
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
